[tools]
"java" = "zulu-21"
"node" = "22"
"poetry" = "latest"
"python" = "3.13"
"sqlite" = "3"
"npm:vercel" = "latest"

[hooks]
postinstall = "corepack enable"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
